
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Doenca` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Doenca
 * 
 */
export type DoencaModel = runtime.Types.Result.DefaultSelection<Prisma.$DoencaPayload>

export type AggregateDoenca = {
  _count: DoencaCountAggregateOutputType | null
  _avg: DoencaAvgAggregateOutputType | null
  _sum: DoencaSumAggregateOutputType | null
  _min: DoencaMinAggregateOutputType | null
  _max: DoencaMaxAggregateOutputType | null
}

export type DoencaAvgAggregateOutputType = {
  id: number | null
}

export type DoencaSumAggregateOutputType = {
  id: number | null
}

export type DoencaMinAggregateOutputType = {
  id: number | null
  nome: string | null
  cid: string | null
}

export type DoencaMaxAggregateOutputType = {
  id: number | null
  nome: string | null
  cid: string | null
}

export type DoencaCountAggregateOutputType = {
  id: number
  nome: number
  cid: number
  _all: number
}


export type DoencaAvgAggregateInputType = {
  id?: true
}

export type DoencaSumAggregateInputType = {
  id?: true
}

export type DoencaMinAggregateInputType = {
  id?: true
  nome?: true
  cid?: true
}

export type DoencaMaxAggregateInputType = {
  id?: true
  nome?: true
  cid?: true
}

export type DoencaCountAggregateInputType = {
  id?: true
  nome?: true
  cid?: true
  _all?: true
}

export type DoencaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Doenca to aggregate.
   */
  where?: Prisma.DoencaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Doencas to fetch.
   */
  orderBy?: Prisma.DoencaOrderByWithRelationInput | Prisma.DoencaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DoencaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Doencas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Doencas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Doencas
  **/
  _count?: true | DoencaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DoencaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DoencaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DoencaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DoencaMaxAggregateInputType
}

export type GetDoencaAggregateType<T extends DoencaAggregateArgs> = {
      [P in keyof T & keyof AggregateDoenca]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDoenca[P]>
    : Prisma.GetScalarType<T[P], AggregateDoenca[P]>
}




export type DoencaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DoencaWhereInput
  orderBy?: Prisma.DoencaOrderByWithAggregationInput | Prisma.DoencaOrderByWithAggregationInput[]
  by: Prisma.DoencaScalarFieldEnum[] | Prisma.DoencaScalarFieldEnum
  having?: Prisma.DoencaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DoencaCountAggregateInputType | true
  _avg?: DoencaAvgAggregateInputType
  _sum?: DoencaSumAggregateInputType
  _min?: DoencaMinAggregateInputType
  _max?: DoencaMaxAggregateInputType
}

export type DoencaGroupByOutputType = {
  id: number
  nome: string
  cid: string | null
  _count: DoencaCountAggregateOutputType | null
  _avg: DoencaAvgAggregateOutputType | null
  _sum: DoencaSumAggregateOutputType | null
  _min: DoencaMinAggregateOutputType | null
  _max: DoencaMaxAggregateOutputType | null
}

export type GetDoencaGroupByPayload<T extends DoencaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DoencaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DoencaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DoencaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DoencaGroupByOutputType[P]>
      }
    >
  >



export type DoencaWhereInput = {
  AND?: Prisma.DoencaWhereInput | Prisma.DoencaWhereInput[]
  OR?: Prisma.DoencaWhereInput[]
  NOT?: Prisma.DoencaWhereInput | Prisma.DoencaWhereInput[]
  id?: Prisma.IntFilter<"Doenca"> | number
  nome?: Prisma.StringFilter<"Doenca"> | string
  cid?: Prisma.StringNullableFilter<"Doenca"> | string | null
}

export type DoencaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  cid?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.DoencaOrderByRelevanceInput
}

export type DoencaWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.DoencaWhereInput | Prisma.DoencaWhereInput[]
  OR?: Prisma.DoencaWhereInput[]
  NOT?: Prisma.DoencaWhereInput | Prisma.DoencaWhereInput[]
  nome?: Prisma.StringFilter<"Doenca"> | string
  cid?: Prisma.StringNullableFilter<"Doenca"> | string | null
}, "id">

export type DoencaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  cid?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DoencaCountOrderByAggregateInput
  _avg?: Prisma.DoencaAvgOrderByAggregateInput
  _max?: Prisma.DoencaMaxOrderByAggregateInput
  _min?: Prisma.DoencaMinOrderByAggregateInput
  _sum?: Prisma.DoencaSumOrderByAggregateInput
}

export type DoencaScalarWhereWithAggregatesInput = {
  AND?: Prisma.DoencaScalarWhereWithAggregatesInput | Prisma.DoencaScalarWhereWithAggregatesInput[]
  OR?: Prisma.DoencaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DoencaScalarWhereWithAggregatesInput | Prisma.DoencaScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Doenca"> | number
  nome?: Prisma.StringWithAggregatesFilter<"Doenca"> | string
  cid?: Prisma.StringNullableWithAggregatesFilter<"Doenca"> | string | null
}

export type DoencaCreateInput = {
  nome: string
  cid?: string | null
}

export type DoencaUncheckedCreateInput = {
  id?: number
  nome: string
  cid?: string | null
}

export type DoencaUpdateInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DoencaUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DoencaCreateManyInput = {
  id?: number
  nome: string
  cid?: string | null
}

export type DoencaUpdateManyMutationInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DoencaUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DoencaOrderByRelevanceInput = {
  fields: Prisma.DoencaOrderByRelevanceFieldEnum | Prisma.DoencaOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type DoencaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  cid?: Prisma.SortOrder
}

export type DoencaAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DoencaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  cid?: Prisma.SortOrder
}

export type DoencaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  cid?: Prisma.SortOrder
}

export type DoencaSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type DoencaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  cid?: boolean
}, ExtArgs["result"]["doenca"]>



export type DoencaSelectScalar = {
  id?: boolean
  nome?: boolean
  cid?: boolean
}

export type DoencaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nome" | "cid", ExtArgs["result"]["doenca"]>

export type $DoencaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Doenca"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nome: string
    cid: string | null
  }, ExtArgs["result"]["doenca"]>
  composites: {}
}

export type DoencaGetPayload<S extends boolean | null | undefined | DoencaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DoencaPayload, S>

export type DoencaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DoencaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DoencaCountAggregateInputType | true
  }

export interface DoencaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Doenca'], meta: { name: 'Doenca' } }
  /**
   * Find zero or one Doenca that matches the filter.
   * @param {DoencaFindUniqueArgs} args - Arguments to find a Doenca
   * @example
   * // Get one Doenca
   * const doenca = await prisma.doenca.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DoencaFindUniqueArgs>(args: Prisma.SelectSubset<T, DoencaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DoencaClient<runtime.Types.Result.GetResult<Prisma.$DoencaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Doenca that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DoencaFindUniqueOrThrowArgs} args - Arguments to find a Doenca
   * @example
   * // Get one Doenca
   * const doenca = await prisma.doenca.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DoencaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DoencaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DoencaClient<runtime.Types.Result.GetResult<Prisma.$DoencaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Doenca that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoencaFindFirstArgs} args - Arguments to find a Doenca
   * @example
   * // Get one Doenca
   * const doenca = await prisma.doenca.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DoencaFindFirstArgs>(args?: Prisma.SelectSubset<T, DoencaFindFirstArgs<ExtArgs>>): Prisma.Prisma__DoencaClient<runtime.Types.Result.GetResult<Prisma.$DoencaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Doenca that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoencaFindFirstOrThrowArgs} args - Arguments to find a Doenca
   * @example
   * // Get one Doenca
   * const doenca = await prisma.doenca.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DoencaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DoencaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DoencaClient<runtime.Types.Result.GetResult<Prisma.$DoencaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Doencas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoencaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Doencas
   * const doencas = await prisma.doenca.findMany()
   * 
   * // Get first 10 Doencas
   * const doencas = await prisma.doenca.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const doencaWithIdOnly = await prisma.doenca.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DoencaFindManyArgs>(args?: Prisma.SelectSubset<T, DoencaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DoencaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Doenca.
   * @param {DoencaCreateArgs} args - Arguments to create a Doenca.
   * @example
   * // Create one Doenca
   * const Doenca = await prisma.doenca.create({
   *   data: {
   *     // ... data to create a Doenca
   *   }
   * })
   * 
   */
  create<T extends DoencaCreateArgs>(args: Prisma.SelectSubset<T, DoencaCreateArgs<ExtArgs>>): Prisma.Prisma__DoencaClient<runtime.Types.Result.GetResult<Prisma.$DoencaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Doencas.
   * @param {DoencaCreateManyArgs} args - Arguments to create many Doencas.
   * @example
   * // Create many Doencas
   * const doenca = await prisma.doenca.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DoencaCreateManyArgs>(args?: Prisma.SelectSubset<T, DoencaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Doenca.
   * @param {DoencaDeleteArgs} args - Arguments to delete one Doenca.
   * @example
   * // Delete one Doenca
   * const Doenca = await prisma.doenca.delete({
   *   where: {
   *     // ... filter to delete one Doenca
   *   }
   * })
   * 
   */
  delete<T extends DoencaDeleteArgs>(args: Prisma.SelectSubset<T, DoencaDeleteArgs<ExtArgs>>): Prisma.Prisma__DoencaClient<runtime.Types.Result.GetResult<Prisma.$DoencaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Doenca.
   * @param {DoencaUpdateArgs} args - Arguments to update one Doenca.
   * @example
   * // Update one Doenca
   * const doenca = await prisma.doenca.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DoencaUpdateArgs>(args: Prisma.SelectSubset<T, DoencaUpdateArgs<ExtArgs>>): Prisma.Prisma__DoencaClient<runtime.Types.Result.GetResult<Prisma.$DoencaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Doencas.
   * @param {DoencaDeleteManyArgs} args - Arguments to filter Doencas to delete.
   * @example
   * // Delete a few Doencas
   * const { count } = await prisma.doenca.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DoencaDeleteManyArgs>(args?: Prisma.SelectSubset<T, DoencaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Doencas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoencaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Doencas
   * const doenca = await prisma.doenca.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DoencaUpdateManyArgs>(args: Prisma.SelectSubset<T, DoencaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Doenca.
   * @param {DoencaUpsertArgs} args - Arguments to update or create a Doenca.
   * @example
   * // Update or create a Doenca
   * const doenca = await prisma.doenca.upsert({
   *   create: {
   *     // ... data to create a Doenca
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Doenca we want to update
   *   }
   * })
   */
  upsert<T extends DoencaUpsertArgs>(args: Prisma.SelectSubset<T, DoencaUpsertArgs<ExtArgs>>): Prisma.Prisma__DoencaClient<runtime.Types.Result.GetResult<Prisma.$DoencaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Doencas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoencaCountArgs} args - Arguments to filter Doencas to count.
   * @example
   * // Count the number of Doencas
   * const count = await prisma.doenca.count({
   *   where: {
   *     // ... the filter for the Doencas we want to count
   *   }
   * })
  **/
  count<T extends DoencaCountArgs>(
    args?: Prisma.Subset<T, DoencaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DoencaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Doenca.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoencaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DoencaAggregateArgs>(args: Prisma.Subset<T, DoencaAggregateArgs>): Prisma.PrismaPromise<GetDoencaAggregateType<T>>

  /**
   * Group by Doenca.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoencaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DoencaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DoencaGroupByArgs['orderBy'] }
      : { orderBy?: DoencaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DoencaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDoencaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Doenca model
 */
readonly fields: DoencaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Doenca.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DoencaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Doenca model
 */
export interface DoencaFieldRefs {
  readonly id: Prisma.FieldRef<"Doenca", 'Int'>
  readonly nome: Prisma.FieldRef<"Doenca", 'String'>
  readonly cid: Prisma.FieldRef<"Doenca", 'String'>
}
    

// Custom InputTypes
/**
 * Doenca findUnique
 */
export type DoencaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Doenca
   */
  select?: Prisma.DoencaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Doenca
   */
  omit?: Prisma.DoencaOmit<ExtArgs> | null
  /**
   * Filter, which Doenca to fetch.
   */
  where: Prisma.DoencaWhereUniqueInput
}

/**
 * Doenca findUniqueOrThrow
 */
export type DoencaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Doenca
   */
  select?: Prisma.DoencaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Doenca
   */
  omit?: Prisma.DoencaOmit<ExtArgs> | null
  /**
   * Filter, which Doenca to fetch.
   */
  where: Prisma.DoencaWhereUniqueInput
}

/**
 * Doenca findFirst
 */
export type DoencaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Doenca
   */
  select?: Prisma.DoencaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Doenca
   */
  omit?: Prisma.DoencaOmit<ExtArgs> | null
  /**
   * Filter, which Doenca to fetch.
   */
  where?: Prisma.DoencaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Doencas to fetch.
   */
  orderBy?: Prisma.DoencaOrderByWithRelationInput | Prisma.DoencaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Doencas.
   */
  cursor?: Prisma.DoencaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Doencas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Doencas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Doencas.
   */
  distinct?: Prisma.DoencaScalarFieldEnum | Prisma.DoencaScalarFieldEnum[]
}

/**
 * Doenca findFirstOrThrow
 */
export type DoencaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Doenca
   */
  select?: Prisma.DoencaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Doenca
   */
  omit?: Prisma.DoencaOmit<ExtArgs> | null
  /**
   * Filter, which Doenca to fetch.
   */
  where?: Prisma.DoencaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Doencas to fetch.
   */
  orderBy?: Prisma.DoencaOrderByWithRelationInput | Prisma.DoencaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Doencas.
   */
  cursor?: Prisma.DoencaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Doencas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Doencas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Doencas.
   */
  distinct?: Prisma.DoencaScalarFieldEnum | Prisma.DoencaScalarFieldEnum[]
}

/**
 * Doenca findMany
 */
export type DoencaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Doenca
   */
  select?: Prisma.DoencaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Doenca
   */
  omit?: Prisma.DoencaOmit<ExtArgs> | null
  /**
   * Filter, which Doencas to fetch.
   */
  where?: Prisma.DoencaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Doencas to fetch.
   */
  orderBy?: Prisma.DoencaOrderByWithRelationInput | Prisma.DoencaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Doencas.
   */
  cursor?: Prisma.DoencaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Doencas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Doencas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Doencas.
   */
  distinct?: Prisma.DoencaScalarFieldEnum | Prisma.DoencaScalarFieldEnum[]
}

/**
 * Doenca create
 */
export type DoencaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Doenca
   */
  select?: Prisma.DoencaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Doenca
   */
  omit?: Prisma.DoencaOmit<ExtArgs> | null
  /**
   * The data needed to create a Doenca.
   */
  data: Prisma.XOR<Prisma.DoencaCreateInput, Prisma.DoencaUncheckedCreateInput>
}

/**
 * Doenca createMany
 */
export type DoencaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Doencas.
   */
  data: Prisma.DoencaCreateManyInput | Prisma.DoencaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Doenca update
 */
export type DoencaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Doenca
   */
  select?: Prisma.DoencaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Doenca
   */
  omit?: Prisma.DoencaOmit<ExtArgs> | null
  /**
   * The data needed to update a Doenca.
   */
  data: Prisma.XOR<Prisma.DoencaUpdateInput, Prisma.DoencaUncheckedUpdateInput>
  /**
   * Choose, which Doenca to update.
   */
  where: Prisma.DoencaWhereUniqueInput
}

/**
 * Doenca updateMany
 */
export type DoencaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Doencas.
   */
  data: Prisma.XOR<Prisma.DoencaUpdateManyMutationInput, Prisma.DoencaUncheckedUpdateManyInput>
  /**
   * Filter which Doencas to update
   */
  where?: Prisma.DoencaWhereInput
  /**
   * Limit how many Doencas to update.
   */
  limit?: number
}

/**
 * Doenca upsert
 */
export type DoencaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Doenca
   */
  select?: Prisma.DoencaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Doenca
   */
  omit?: Prisma.DoencaOmit<ExtArgs> | null
  /**
   * The filter to search for the Doenca to update in case it exists.
   */
  where: Prisma.DoencaWhereUniqueInput
  /**
   * In case the Doenca found by the `where` argument doesn't exist, create a new Doenca with this data.
   */
  create: Prisma.XOR<Prisma.DoencaCreateInput, Prisma.DoencaUncheckedCreateInput>
  /**
   * In case the Doenca was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DoencaUpdateInput, Prisma.DoencaUncheckedUpdateInput>
}

/**
 * Doenca delete
 */
export type DoencaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Doenca
   */
  select?: Prisma.DoencaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Doenca
   */
  omit?: Prisma.DoencaOmit<ExtArgs> | null
  /**
   * Filter which Doenca to delete.
   */
  where: Prisma.DoencaWhereUniqueInput
}

/**
 * Doenca deleteMany
 */
export type DoencaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Doencas to delete
   */
  where?: Prisma.DoencaWhereInput
  /**
   * Limit how many Doencas to delete.
   */
  limit?: number
}

/**
 * Doenca without action
 */
export type DoencaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Doenca
   */
  select?: Prisma.DoencaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Doenca
   */
  omit?: Prisma.DoencaOmit<ExtArgs> | null
}
